### ISSUE TITLE
Period is getting removed during tokenization?

### ISSUE THREAD

**Issue by neurosnap** [michigan-com/summarizer#4]
https://api.michigan.com/v1/article/75995706/

Goaltender Petr Mrazek turned aside 15 Ovechkin shots the last time the teams played (Nov. 10), a 1-0 Red Wings victory.\nThere’s not much of a plan or strategy, said Mrazek, other than being ready for the challenge.

turns into:

Goaltender Petr Mrazek turned aside 15 Ovechkin shots the last time the teams played (Nov. 10), a 1-0 Red Wings victory There’s not much of a plan or strategy, said Mrazek, other than being ready for the challenge.

**Comment by migreva** [comment]
https://www.youtube.com/watch?v=UtVjRG7PB_4&feature=youtu.be&t=9s

**Comment by neurosnap** [comment]
Haven't seen this since, can't replicate in summarizer, going to close issue for now.
